steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'functions', 'deploy', 'telegram-test', '--gen2', '--region=europe-west1', '--runtime=python39', '--trigger-http', '--env-vars-file', 'env.yaml', '--project=endpoint-test-telegram', '--memory', '1024M', '--entry-point=entry', '--service-account=testbot@endpoint-test-telegram.iam.gserviceaccount.com']

#  args:
#  - 'functions'
#  - 'deploy'
#  - 'telegram-test'
#  - 'gen2'
#  - 'region'
#  - 'europe-west1'
#  - 'runtime'
#  - 'python39'
#  - 'trigger-http'
#  - 'env-vars-file'
#  - 'env.yaml'
#  - 'project'
#  - 'endpoint-test-telegram'
#  - 'memory'
#  - '1024M'
#  - 'entry-point'
#  - 'entry'
#  - 'service-account'
#  - 'testbot@endpoint-test-telegram.iam.gserviceaccount.com'

# cloud functions deploy telegram-test --gen2 --region=europe-west1 --runtime=python39 --trigger-http
# --env-vars-file env.yaml --project=endpoint-test-telegram --memory 1024M --timeout=1m --entry-point=entry
# --service-account=testbot@endpoint-test-telegram.iam.gserviceaccount.com
# --run-service-account=testbot@endpoint-test-telegram.iam.gserviceaccount.com

#    env:
#      PROJECT_ID: 'endpoint-test-telegram'
#      SERVICE: 'testbot@endpoint-test-telegram.iam.gserviceaccount.com'
#      REGION: 'europe-west1'
#
#    jobs:
#      deploy:
#        # Add 'id-token' with the intended permissions for workload identity federation
#        permissions:
#          contents: 'read'
#          id-token: 'write'
#
#        runs-on: ubuntu-latest
#        steps:
#          - name: Checkout
#            uses: actions/checkout@v2
#
#
#          - name: Google Auth
#            id: auth
#            uses: 'google-github-actions/auth@v0'
#            with:
#              credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
#
#          - name: Deploy to Cloud Run
#            id: deploy
#            uses: google-github-actions/deploy-cloud-functions@v1
#            with:
#              name: 'telegram-test'
#              region: ${{ env.REGION }}
#              source_dir: ./
#              runtime: 'python39'
#              entry_point: 'entry'
#              env_vars_file: 'env.yaml'
#              project_id: ${{ env.PROJECT_ID }}
#              memory_mb: '1024'
#              service_account_email: ${{ env.SERVICE }}
#
#
#          # If required, use the Cloud Run url output in later steps
#          - name: Show Output
#            run: echo ${{ steps.deploy.outputs.url }}