steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'functions', 'deploy', 'telegram-test', '--gen2', '--region=europe-west1', '--runtime=python39', '--trigger-http', '--env-vars-file', 'env.yaml', '--project=endpoint-test-telegram', '--memory', '1024M', '--entry-point=entry', '--service-account=testbot@endpoint-test-telegram.iam.gserviceaccount.com']